### ISSUE TITLE
Nothing happens on submit

### ISSUE THREAD

**Issue by blauertee** [benbalter/word-to-markdown-js#48]
### Describe the bug

I was trying to use [this](https://word2md.com/?) online Version of the tool. When uploading a file I get the following exception in the Console. When clicking the submit button the file is gone and everything looks as if I just opened the page.

<details>
<summary>Firefox Traceback</summary>
```
Uncaught (in promise) TypeError: o is undefined
    convertXmlToDocument https://word2md.com/main.js:1
    read https://word2md.com/main.js:1
    flatMap https://word2md.com/main.js:1
    read https://word2md.com/main.js:1
    flatMap https://word2md.com/main.js:1
    read https://word2md.com/main.js:1
    D https://word2md.com/main.js:1
    promise callback*175/D/< https://word2md.com/main.js:1
    promise callback*D https://word2md.com/main.js:1
    read https://word2md.com/main.js:1
    s https://word2md.com/main.js:1
    _settlePromiseFromHandler https://word2md.com/main.js:1
    _settlePromise https://word2md.com/main.js:1
    _settlePromise0 https://word2md.com/main.js:1
    _settlePromises https://word2md.com/main.js:1
    _fulfill https://word2md.com/main.js:1
    _resolveCallback https://word2md.com/main.js:1
    _settlePromiseFromHandler https://word2md.com/main.js:1
    _settlePromise https://word2md.com/main.js:1
    _settlePromise0 https://word2md.com/main.js:1
    _settlePromises https://word2md.com/main.js:1
    _fulfill https://word2md.com/main.js:1
    _resolve https://word2md.com/main.js:1
    _promiseFulfilled https://word2md.com/main.js:1
    _settlePromise https://word2md.com/main.js:1
    _settlePromise0 https://word2md.com/main.js:1
    _settlePromises https://word2md.com/main.js:1
    _drainQueue https://word2md.com/main.js:1
    _drainQueues https://word2md.com/main.js:1
    drainQueues https://word2md.com/main.js:1
    promise callback*r https://word2md.com/main.js:1
    _queueTick https://word2md.com/main.js:1
    u https://word2md.com/main.js:1
    _fulfill https://word2md.com/main.js:1
    _resolveCallback https://word2md.com/main.js:1
    l https://word2md.com/main.js:1
    promise callback*s https://word2md.com/main.js:1
    exports https://word2md.com/main.js:1
```
</details>

<details>
<summary>Chromium Traceback</summary>

```
main.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at Object.convertXmlToDocument (main.js:1:671752)
    at main.js:1:672858
    at i.flatMap (main.js:1:687197)
    at main.js:1:672789
    at i.flatMap (main.js:1:687197)
    at main.js:1:672750
    at main.js:1:674595
convertXmlToDocument @ main.js:1
(anonymous) @ main.js:1
i.flatMap @ main.js:1
(anonymous) @ main.js:1
i.flatMap @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
s @ main.js:1
(anonymous) @ main.js:1
r @ main.js:1
e.onload @ main.js:1
load (async)
(anonymous) @ main.js:1
(anonymous) @ main.js:1
r @ main.js:1
ta @ main.js:1
```

</details>

### Steps to reproduce the behavior

1. Upload .doc file
2. Click submit

### Expected behavior

Getting a markdown version of the word document

### Additional context

Happens on Firefox 120.0 and Chromium 119.0.6045.159 on a Debian system.

**Comment by blauertee** [comment]
Maybe this should have gone [here](https://github.com/benbalter/word-to-markdown-server) not sure :)

**Comment by AngryPhantom** [comment]
I can confirm this. The site word2md.com doesn't work for me either.

**Comment by benbalter** [comment]
Should be working now, please shout if that's not the case?

**Comment by AngryPhantom** [comment]
@benbalter 

Stil doesn't work for me. Upload the file, press Submit and nothing...

I've tried it in different versions of Firefox and Chrome.

The file is here in case you'd like to test it yourself.

[Essay.doc](https://github.com/user-attachments/files/22532131/Essay.doc)

**Comment by benbalter** [comment]
@AngryPhantom I see what's going on. You're uploading a `.doc` file, but the converter only supports `.docx` files. I've opened https://github.com/benbalter/word-to-markdown-js/issues/88 to make that more user friendly. Hopefully you can convert it to a `.docx` file.

**Comment by benbalter** [comment]
@AngryPhantom That's understandable. A previous version supported .doc files. The text has been removed, and if you try with your file now, you will see:

<img width="837" height="159" alt="Image" src="https://github.com/user-attachments/assets/fd17115d-59b0-4af3-b546-542b13e0675b" />
